#
# The Short URL Reservation Production Service
# (Copyright 2024 by Richard Klein)
#
version = 0.1
[default.deploy.parameters]
stack_name = "short-url-reservation-service-prod"
s3_bucket = "short-url-artifacts"
s3_prefix = "short-url-reservation-service-prod"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = false
confirm_changeset = false
parameter_overrides = "Profile=prod"
