AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL Reservation Service - api.richarddklein.com/shorturl/reservations
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ShortUrlReservationService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturlreservationservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Timeout: 90
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/range
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/tableName
      SnapStart:
        ApplyOn: "PublishedVersions"
      Events:
        InitializeShortUrlReservationTableViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/all
            Method: POST
        InitializeShortUrlReservationTableViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: POST
        GetAllShortUrlsViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/all
            Method: GET
        GetAllShortUrlsViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: GET
        GetSpecificShortUrlViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/specific/{proxy+}
            Method: GET
        GetSpecificShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /specific/{proxy+}
            Method: GET
        ReserveAnyShortUrlViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/reserve/any
            Method: PUT
        ReserveAnyShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /reserve/any
            Method: PUT
        ReserveSpecificShortUrlViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/reserve/specific/{proxy+}
            Method: PUT
        ReserveSpecificShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /reserve/specific/{proxy+}
            Method: PUT
        ReserveAllShortUrlsViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/reserve/all
            Method: PUT
        ReserveAllShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /reserve/all
            Method: PUT
        CancelSpecificShortUrlReservationViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/cancel/specific/{proxy+}
            Method: PUT
        CancelSpecificShortUrlReservationViaCustomDomain:
          Type: Api
          Properties:
            Path: /cancel/specific/{proxy+}
            Method: PUT
        CancelAllShortUrlReservationsViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/cancel/all
            Method: PUT
        CancelAllShortUrlReservationsViaCustomDomain:
          Type: Api
          Properties:
            Path: /cancel/all
            Method: PUT
