AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL Reservation Service - api.richarddklein.com/shorturl/reservation
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ShortUrlReservationService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturlreservationservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      SnapStart:
        ApplyOn: "PublishedVersions"
      Events:
        ReserveAnyShortUrl:
          Type: Api
          Properties:
            Path: /shorturl/reservations
            Method: GET
        ReserveSpecifiedShortUrl:
          Type: Api
          Properties:
            Path: /shorturl/reservations/{proxy+}
            Method: GET
        CancelShortUrlReservation:
          Type: Api
          Properties:
            Path: /shorturl/reservations/{proxy+}
            Method: DELETE

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shorturl/reservations'
    Export:
      Name: ShortUrlReservationServiceApi
