AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL Reservation Service - api.richarddklein.com/shorturl/reservations
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ShortUrlReservationService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturlreservationservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 90
      SnapStart:
        ApplyOn: "PublishedVersions"
      Events:
        InitializeShortUrlReservationTableViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/all
            Method: POST
        InitializeShortUrlReservationTableViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: POST
        GetAllShortUrlsViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/all
            Method: GET
        GetAllShortUrlsViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: GET
        GetSpecificShortUrlViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/specific/{proxy+}
            Method: GET
        GetSpecificShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /specific/{proxy+}
            Method: GET
        ReserveAnyShortUrlViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/reserve/any
            Method: PUT
        ReserveAnyShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /reserve/any
            Method: PUT
        ReserveSpecificShortUrlViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/reserve/{proxy+}
            Method: PUT
        ReserveSpecificShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /reserve/{proxy+}
            Method: PUT
        CancelSpecificShortUrlReservationViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/cancel/{proxy+}
            Method: PUT
        CancelSpecificShortUrlReservationViaCustomDomain:
          Type: Api
          Properties:
            Path: /cancel/{proxy+}
            Method: PUT
