#
# The Short URL Reservation Service
# (Copyright 2024 by Richard Klein)
#
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL Reservation Service - api.richarddklein.com/shorturl/reservations
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ShortUrlReservationService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturlreservationservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Timeout: 90
      Policies:
        # Write permission for CloudWatch logs
        - AWSLambdaBasicExecutionRole
        # Read/write permission for DynamoDB
        - AmazonDynamoDBFullAccess
        # Read permission for SSM Parameter Store.
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/reservations/tableName
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/reservations/range
      SnapStart:
        ApplyOn: "PublishedVersions"

      # Defined below are the REST endpoints. For each endpoint, a pair of
      # paths are defined. One path is for the case where the URL specifies
      # either the API Gateway or localhost. The other path is for the case
      # where the URL specifies the custom domain that redirects to the API
      # Gateway. Thus, an endpoint URL can have one of three possible values:
      #
      # API Gateway:   <aws-api-ID>.execute-api.us-east-2.amazonaws.com/Prod/shorturl/reservations/<endpoint>
      # localhost:     localhost:4000/shorturl/reservations/<endpoint>
      # Custom Domain: api.richarddklein.com/shorturl/reservations/<endpoint>
      #
      # When the service is running on your local machine, via the command
      # `sam local start-api`, use the above `localhost` URL.
      #
      # When the service is running on AWS, use either the above `API Gateway`
      # URL or the above `Custom Domain` URL. (It is recommended that you use
      # the `Custom Domain` hostname, as it is simpler to remember and to type.)
      #
      # For a description of the functionality provided by the REST endpoints,
      # see the comments in the `ShortUrlReservationController` interface.
      Events:
        InitializeShortUrlReservationTableViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/reservations/dbinit
            Method: POST
        InitializeShortUrlReservationTableViaCustomDomain:
          Type: Api
          Properties:
            Path: /dbinit
            Method: POST
        GetSpecificShortUrlViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/reservations/specific/{proxy+}
            Method: GET
        GetSpecificShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /specific/{proxy+}
            Method: GET
        GetAllShortUrlsViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/reservations/all
            Method: GET
        GetAllShortUrlsViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: GET
        ReserveAnyShortUrlViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/reservations/reserve/any
            Method: PATCH
        ReserveAnyShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /reserve/any
            Method: PATCH
        ReserveSpecificShortUrlViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/reservations/reserve/specific/{proxy+}
            Method: PATCH
        ReserveSpecificShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /reserve/specific/{proxy+}
            Method: PATCH
        ReserveAllShortUrlsViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/reservations/reserve/all
            Method: PATCH
        ReserveAllShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /reserve/all
            Method: PATCH
        CancelSpecificShortUrlReservationViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/reservations/cancel/specific/{proxy+}
            Method: PATCH
        CancelSpecificShortUrlReservationViaCustomDomain:
          Type: Api
          Properties:
            Path: /cancel/specific/{proxy+}
            Method: PATCH
        CancelAllShortUrlReservationsViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/reservations/cancel/all
            Method: PATCH
        CancelAllShortUrlReservationsViaCustomDomain:
          Type: Api
          Properties:
            Path: /cancel/all
            Method: PATCH
