AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL Reservaation Service - api.richarddklein.com/shorturl/reservation
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ShortUrlReservationService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturlreservationservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      SnapStart:
        ApplyOn: "PublishedVersions"
      Events:
        RootResource:
          Type: Api
          Properties:
            Path: /shorturl/reservation
            Method: any
        ProxyResource:
          Type: Api
          Properties:
            Path: /shorturl/reservation/{proxy+}
            Method: any

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shorturl/reservation'
    Export:
      Name: ShortUrlReservationServiceApi
