AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL Reservation Service - api.richarddklein.com/shorturl/reservations
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ShortUrlReservationService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturlreservationservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 90
      SnapStart:
        ApplyOn: "PublishedVersions"
      Events:
        InitializeShortUrlReservationTableViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/all
            Method: POST
        InitializeShortUrlReservationTableViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: POST
        GetAllShortUrlsViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/all
            Method: GET
        GetAllShortUrlsViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: GET
        ReserveAnyShortUrlViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations
            Method: GET
        ReserveAnyShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /
            Method: GET
        ReserveSpecifiedShortUrlViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/{proxy+}
            Method: GET
        ReserveSpecifiedShortUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
        CancelShortUrlReservationViaApiGateway:
          Type: Api
          Properties:
            Path: /shorturl/reservations/{proxy+}
            Method: DELETE
        CancelShortUrlReservationViaCustomDomain:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: DELETE
